"""教学示例：一张有自增主键、唯一约束与可空字段的单表。

注意 Identity() 的写法：PostgreSQL 上这等价于
``GENERATED BY DEFAULT AS IDENTITY``，与 ``SERIAL`` / ``BIGSERIAL`` 完全不同。
SQLAlchemy autogenerate 能正确识别这种定义，迁移文件里看到 ``sa.Identity()``
而不是手写 ``nextval(...)``。
"""
# ↑ 模块 docstring：解释这是"学生表"的 ORM 模型，并强调主键用 Identity 而非 SERIAL。

# 导入三种列类型：
#   BigInteger 大整数（对应 bigint）、Identity 自增主键、String 变长字符串。
from sqlalchemy import BigInteger, Identity, String

# 导入 SQLAlchemy 2 的标准 ORM 写法：Mapped 类型标注 + mapped_column 列定义。
from sqlalchemy.orm import Mapped, mapped_column

# 导入 ORM 基类（所有表都要继承它）。
from app.db.base import Base


class StuTable(Base):
    # ↑ 定义"学生表"模型类，继承 Base（自动带上 Schema 和命名约定）。

    __tablename__ = "stu_table"
    # ↑ 指定这张表在数据库里的名字。

    __table_args__ = {"comment": "学生基本信息表"}
    # ↑ 表级别的额外参数：这里给整张表加个注释（comment）。

    # BigInteger + PostgreSQL IDENTITY：明确告知 SQLAlchemy 用 IDENTITY 生成主键。
    # 不要写 autoincrement=True：那是 SQLAlchemy 1.x 的 SERIAL 习惯，
    # 与 PostgreSQL 的 IDENTITY 不等价，且会让 autogenerate 误判。
    # ↑ 设计说明：强调主键写法（阶段 4 重点）。
    stu_id: Mapped[int] = mapped_column(
        # ↑ 定义"学生主键 ID"列，类型是 int（映射到数据库 bigint）。
        BigInteger,
        # ↑ 数据库列类型用 BigInteger（大整数）。
        Identity(always=False),
        # ↑ 用 IDENTITY 生成自增值；always=False 表示允许手动插入（BY DEFAULT）。
        primary_key=True,
        # ↑ 设为主键。
        comment="学生信息主键ID",
        # ↑ 列注释。
    )

    # 学号：NOT NULL + UNIQUE。唯一约束名由 Base 中的命名规则生成。
    # ↑ 说明：学号不允许为空，且不允许重复。
    stu_number: Mapped[str] = mapped_column(
        # ↑ 定义"学号"列，类型 str。
        String(32),
        nullable=False,
        unique=True,
        comment="学生学号",
        # ↑ String(32)：最长 32 字符；nullable=False：不能为空；unique=True：唯一。
    )

    # 姓名：必填、不唯一。
    # ↑ 说明：姓名必填，但可以重名。
    stu_name: Mapped[str] = mapped_column(String(100), nullable=False, comment="学生姓名")
    # ↑ 定义"姓名"列，最长 100 字符，不能为空。

    # 班级 / 专业 / 学院：可空字符串。
    # ↑ 说明：这三个字段可以为空（学生信息可能还没填）。
    stu_class: Mapped[str | None] = mapped_column(String(100), nullable=True, comment="学生班级")
    # ↑ "班级"列，可空（类型标注 str | None 表示可能是字符串也可能是 None）。
    stu_major: Mapped[str | None] = mapped_column(String(100), nullable=True, comment="学生专业")
    # ↑ "专业"列，可空。
    stu_college: Mapped[str | None] = mapped_column(String(150), nullable=True, comment="学生学院")
    # ↑ "学院"列，可空。

    # 联系方式字段。长度按实际用途限定。
    # ↑ 说明：下面是三个联系方式字段。
    stu_phone: Mapped[str | None] = mapped_column(String(32), nullable=True, comment="学生手机号")
    # ↑ "手机号"列，可空。
    stu_email: Mapped[str | None] = mapped_column(String(255), nullable=True, comment="学生邮箱")
    # ↑ "邮箱"列，可空。
    stu_address: Mapped[str | None] = mapped_column(String(255), nullable=True, comment="学生地址")
    # ↑ "地址"列，可空。
