"""教学示例：一张有自增主键、唯一约束与可空字段的单表。

注意 Identity() 的写法：PostgreSQL 上这等价于
``GENERATED BY DEFAULT AS IDENTITY``，与 ``SERIAL`` / ``BIGSERIAL`` 完全不同。
SQLAlchemy autogenerate 能正确识别这种定义，迁移文件里看到 ``sa.Identity()``
而不是手写 ``nextval(...)``。
"""

from sqlalchemy import BigInteger, Identity, String
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base


class StuTable(Base):
    __tablename__ = "stu_table"
    __table_args__ = {"comment": "学生基本信息表"}

    # BigInteger + PostgreSQL IDENTITY：明确告知 SQLAlchemy 用 IDENTITY 生成主键。
    # 不要写 autoincrement=True：那是 SQLAlchemy 1.x 的 SERIAL 习惯，
    # 与 PostgreSQL 的 IDENTITY 不等价，且会让 autogenerate 误判。
    stu_id: Mapped[int] = mapped_column(
        BigInteger,
        Identity(always=False),
        primary_key=True,
        comment="学生信息主键ID",
    )

    # 学号：NOT NULL + UNIQUE。唯一约束名由 Base 中的命名规则生成。
    stu_number: Mapped[str] = mapped_column(
        String(32), nullable=False, unique=True, comment="学生学号"
    )

    # 姓名：必填、不唯一。
    stu_name: Mapped[str] = mapped_column(String(100), nullable=False, comment="学生姓名")

    # 班级 / 专业 / 学院：可空字符串。
    stu_class: Mapped[str | None] = mapped_column(String(100), nullable=True, comment="学生班级")
    stu_major: Mapped[str | None] = mapped_column(String(100), nullable=True, comment="学生专业")
    stu_college: Mapped[str | None] = mapped_column(String(150), nullable=True, comment="学生学院")

    # 联系方式字段。长度按实际用途限定。
    stu_phone: Mapped[str | None] = mapped_column(String(32), nullable=True, comment="学生手机号")
    stu_email: Mapped[str | None] = mapped_column(String(255), nullable=True, comment="学生邮箱")
    stu_address: Mapped[str | None] = mapped_column(String(255), nullable=True, comment="学生地址")
