"""教学示例：照搬学习项目里 test.stu_table 的真实列。

已经按 PostgreSQL 实际列定义对齐：字段注释 / 唯一约束 / 是否可空 / 长度。
alembic check 在该模型下应报告"无差异"，方便后面用 stamp head 把库打上迁移基线。
"""

from sqlalchemy import BigInteger, String
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base


class StuTable(Base):
    __tablename__ = "stu_table"
    # 表级注释与数据库一致；增删字段时这里也要同步改。
    __table_args__ = {"comment": "学生基本信息表"}

    # bigint 主键 NOT NULL；PostgreSQL 默认 GENERATED BY DEFAULT AS IDENTITY 自增。
    # 这一列在数据库里就是 IDENTITY，不再写 SERIAL/BIGSERIAL。
    stu_id: Mapped[int] = mapped_column(
        BigInteger,
        primary_key=True,
        autoincrement=True,
        comment="学生信息主键ID",
    )

    # 学号：32 位变长字符串，NOT NULL + UNIQUE（DB 上是 uq_stu_table_stu_number）。
    # 唯一约束的命名由 Base 中的统一命名规则生成；不需要再传 name=。
    stu_number: Mapped[str] = mapped_column(
        String(32), nullable=False, unique=True, comment="学生学号"
    )

    # 姓名：必填，不唯一。
    stu_name: Mapped[str] = mapped_column(
        String(100), nullable=False, comment="学生姓名"
    )

    # 班级 / 专业 / 学院：可空字符串。学生尚未分班时允许 NULL。
    stu_class: Mapped[str | None] = mapped_column(
        String(100), nullable=True, comment="学生班级"
    )
    stu_major: Mapped[str | None] = mapped_column(
        String(100), nullable=True, comment="学生专业"
    )
    stu_college: Mapped[str | None] = mapped_column(
        String(150), nullable=True, comment="学生学院"
    )

    # 联系方式：电话 32 位足够国际区号；邮箱限 255 字符；地址限 255 字符。
    stu_phone: Mapped[str | None] = mapped_column(
        String(32), nullable=True, comment="学生手机号"
    )
    stu_email: Mapped[str | None] = mapped_column(
        String(255), nullable=True, comment="学生邮箱"
    )
    stu_address: Mapped[str | None] = mapped_column(
        String(255), nullable=True, comment="学生地址"
    )